### ISSUE TITLE
how to visualize like paper?

### ISSUE THREAD

**Issue by suker80** [JunweiLiang/FVTA_memoryqa#1]
Hello nice to meet you!

i'm reading about your paper,code and  i don't understand about your  code that how to visualize image like paper??

In paper visualized have highest weight ,how to extract highest weight??

Is correct using "att_logits" with visualize??

**Comment by JunweiLiang** [comment]
Hi, yes, I used "att_logits" to get the retrieval scores for visualization. Specifically, in models_v2.py #1022, "att_logits" is a [N,K,T,JQ] tensor, which means "batch_size"/"modality"/"Time"/"Question word Index". So you can get the heighest attention weight **for each modality** [Album title / Album description / Album Time / Album Location / Photo Title / Photo ]. In the paper I only visualize with **Photo** weights.
