### ISSUE TITLE
Accuracy related to questions starting with 'when'

### ISSUE THREAD

**Issue by ayanavasarkar** [JunweiLiang/FVTA_memoryqa#3]
Hi,

I have been running most of the models and have been consistently getting low accuracies for questions related to 'when'.

Do you have any insights on this or perhaps reasoning to this? Or could it be attributed to the dataset?

**Comment by JunweiLiang** [comment]
This is the case as in our paper:
> Liang, Junwei, Lu Jiang, Liangliang Cao, Yannis Kalantidis, Li-Jia Li, and Alexander G. Hauptmann. "Focal visual-text attention for memex question answering." IEEE transactions on pattern analysis and machine intelligence 41, no. 8 (2019): 1893-1908.

"when" questions are at ~35% accuracy while others are ~60% (multiple-choice setting). The reasons could be two folds: first, for answering "when" questions, the model has to look at multiple modalities ("time" modality plus others) so it is harder; second, the answers for "when" questions are mostly unique so it is not easy for the model to learn from examples.
